export const sdVars = {
  bg: 'var(--sd-bg)',
  bgGrad: 'var(--sd-bg-grad)',
  surface: 'var(--sd-surface)',
  surface2: 'var(--sd-surface2)',
  surface3: 'var(--sd-surface3)',
  border: 'var(--sd-border)',
  borderHi: 'var(--sd-border-hi)',
  borderBright: 'var(--sd-border-bright)',
  text: 'var(--sd-text)',
  textDim: 'var(--sd-text-dim)',
  textMute: 'var(--sd-text-mute)',
  primary: 'var(--sd-primary)',
  primaryDeep: 'var(--sd-primary-deep)',
  danger: 'var(--sd-danger)',
  dangerSoft: 'var(--sd-danger-soft)',
  success: 'var(--sd-success)',
  successSoft: 'var(--sd-success-soft)',
  warning: 'var(--sd-warning)',
  warningSoft: 'var(--sd-warning-soft)',
  fontDisplay: 'var(--sd-font-display)',
  fontBody: 'var(--sd-font-body)',
  fontMono: 'var(--sd-font-mono)',
} as const;
